# action.yml
name: 'Firefly III development tools'
description: 'A GitHub action to help with Firefly III development and release management'
inputs:
  action:
    description: 'Which action to undertake.'
    required: true
    default: ''
  output:
    description: 'Whether or not to return the results of the action.'
    required: false
    default: ''
outputs:
  result:
    description: 'Output of the action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.output }}
