# action.yml
name: 'Firefly III dev tools'
description: 'Run things bla bla bla'
inputs:
  action:  # id of input
    description: 'What to do'
    required: true
    default: ''
  output:  # id of input
    description: 'Give output back'
    required: false
    default: ''
outputs:
  result: # id of output
    description: 'Output of the action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.output }}
